language: node_js
node_js:
  - '10'

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - node_modules
    - packages/*/node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}

deploy:
  - provider: script
    script: yarn publish:canary -- --yes
    skip_cleanup: true
    on:
      branch: master
      tags: false
  - provider: script
    script: yarn publish:fromgit -- --yes
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      tags: true
